### ISSUE TITLE
Insert payload at a point in time in the past

### ISSUE THREAD

**Issue by Exide** [flightstats/hub#491]
I've got data that I want to insert into a channel and specify a timestamp in the past so that it is represented in the item's URI and "Creation-Date" header.

For example, say I want to insert a payload on the last millisecond of 1999. I would like to submit a request similar to this:

    curl -X POST --data "old data" http://hub/channel/foo/1999/12/31/23/59/59/999

**Comment by chriskessel** [comment]
I know a year ago or so there was talk about being able to delete individual items from a hub channel and some folks (myself included) were against it because the contract that history in a hub channel would never change has a lot of value. The use case there was basically using the hub as a name/value pair database, which didn't seem appropriate.

This is another case that would disrupt that "history doesn't change" contract, but the use case here is backfilling a channel with data we've extracted from other sources. We want the channel to look like it was filled correctly back in 2003...even though there was no hub then :)

Since this does mess with channel history, whatever approach should probably be locked down somehow. Perhaps permissions. Perhaps ensuring the inserted item is older than the previous earliest  entry (i.e. no inserting between items). Maybe an admin only "repair" option where another channel is copied into an existing channel? 

Just brainstorming ideas...I don't want to poke a hole in the contract channel's currently provide regarding history without some significant safe guards. We have code running that depends on that contract.

**Comment by breedx2** [comment]
@Exide What's your actual use case?  Why do you want to insert something to make it appear as though it came in at some other (false) time?

**Comment by chriskessel** [comment]
@breedx2 We need to backfill a channel to make it look like the hub was sucking in data back in the early 2000s... (I did note that, but it's in the middle of my tl;dr comment).

Inserting is one solution. As I noted, I'm a bit leery of it for all the same reasons we were leery of supporting item deletion. Got any ideas for another way to go about it? One of the key requirements from our end is having the Hub item URL have an appropriately old looking format.

**Comment by breedx2** [comment]
@chriskessel Ok, but you guys haven't explained _why_ you want (need?) to do that.  What you're proposing is a pretty hardcore change to hub behavior without describing an actual use case.   

You've said you need it, but why do you need it?  Are you planning on directly exposing that to customers or something?  Are you trying to use some existing process that relies on the dates in the urls?  What's the use case?

**Comment by chriskessel** [comment]
> Are you planning on directly exposing that to customers or something? Are you trying to use some existing process that relies on the dates in the urls? 

In short, yes and yes. 

The use case is supporting customer Historical Flight Status and Flight Status Feed requests for data extracted from PFProd. We do have products, like the Flight Status Feed, that effectively exposes the hub URL (well, the time based portions of it). We could change the guts to know that a date older than X would secretly go elsewhere to get the backfilled data. 

However, that is messy and we've got lots of code that relies on hub data being in date appropriate hub URLs. Modifying a channel's history is bad though, so let's brainstorm a way to get old hub URLs without breaking the current channel contract.

Here's one idea. Create a channel from scratch with all the old data "imported" as part of the channel creation. Essentially an atomic channel create with data, versus the channel create that's empty today.  I could then use the hub's channel weave feature to make it looks like that channel and the existing channel are one seamless channel.

Here's another idea. Create a docker instance with a Hub, place all the data on disk in the correctly named data directories to fake the old data urls. Then tell that hub to replicate to the official Hub since replication also replicates the URLs.

Neither of those break the current contract. Any other ideas to throw on the brainstorm pile?

**Comment by moulliet** [comment]
We could have 'historical' as a new channel level option.  It only allows inserts of time stamped historical items.  It has a different contract than normal channels, and therefore could also allow deletes and/or updates.  It could still be weaved together with other channels.

A variation on this would be a channel combo of historical & normal that only applies to specified channels.

The historical data would not go through the normal notification process via callbacks, events, websockets, etc.

**Comment by crozierm** [comment]
I very much like the idea of a back-populated channel being a separate beast. That would allow us to map our archive's timestamp metadata to the channel URLs without perverting the concept of a "normal" channel to be anything other than immutable content, append-only, etc...
