### ISSUE TITLE
Feature Request: Add a before or after option to the time interface

### ISSUE THREAD

**Issue by brettcalvin** [flightstats/hub#677]
We need to find the first hub item that was before a point in time.  We can use the time interface to get that time (probably to the second), get the first item, and do a previous on that.

However, if there are no items in that time bucket, it gets more difficult.  We could have minutes or even hours of gaps in any given channel, so walking back second by second until we find something would be time consuming.  Broadening the request to the minute and then hour would find items sooner, but then we'd have to iterate through the hub items and parse the times out of the URIs to process them.

It would be fantastic to have an interface that we could give a time and get the first item before (or after) that time.  Something like:

http://hub.iad.staging.flightstats.io/channel/ProcessedFlightHistory/2016/12/14/00/28/08/before

**Comment by moulliet** [comment]
@brettcalvin I think the interface already exists.

For any channel, a user can query:
http://hub/channel/name/2016/12/14/00/28/08/000/0/previous
http://hub/channel/name/2016/12/14/00/28/08/000/0/previous/10
http://hub/channel/name/2016/12/14/00/28/08/000/0/next
http://hub/channel/name/2016/12/14/00/28/08/000/0/next/10

The starting point does not need to exist.  
I choose '0' (zero) as my imaginary item's hash because zero is guaranteed to be before any actual hash values.

If it would be useful to have redirects to the above urls from something less than a fully quality starting point, let us know.

**Comment by brettcalvin** [comment]
Sweet, that seems to work great for us.  Thanks!
